# Prerequisite:

python perturbation_analysis.py -ct1 T-cells -ct2 Macrophages -adata /home/sxr280/Spatialformer/downstream/cell_cell_communication/data/croped_sdata_VUILD102LF.h5ad -pair_num 100 -cci /home/sxr280/Spatialformer/downstream/cell_cell_communication/data/VUILD102LF_croped_cell_id.npy -ts Lung -cd Disease -cache_dir /home/sxr280/Spatialformer/cache/ -base_dir /home/sxr280/Spatialformer_6_10 -rd 30 -out_dir /home/sxr280/Spatialformer/downstream/cell_cell_communication/data -sample VUILD102LF

In [2]:
import pickle
import numpy as np
from tqdm import tqdm
import pandas as pd
import sys
sys.path.append("/home/sxr280/Spatialformer_6_10/utils")
from utils import stat_test, ovlp_database, filter_df

/home/sxr280/miniconda3/envs/spatialformer/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
import json
with open("/home/sxr280/Spatialformer_6_10/tokenizer/tokenv4.json", "r") as f:
    vocab = json.load(f)
    vocab = {j:i for i,j in vocab.items()}

In [4]:
all_infos = pickle.load(open("/home/sxr280/Spatialformer/downstream/cell_cell_communication/data/all_infos_crop_id_T-cells_Macrophages_VUILD102LF.pkl", "rb"))
#Optional 1: use the CellChat database
database_path1 = "/home/sxr280/Spatialformer_6_10/downstream/cell_cell_communication/data/ligand_receptor_database.csv"
#Optional 2: use the Cellnest database
database_path2 = "/home/sxr280/Spatialformer_6_10/downstream/cell_cell_communication/data/CellNEST_database.csv"
mac_t_pair_df = stat_test(all_infos, vocab)
mac_t_pair_df = ovlp_database(mac_t_pair_df, database_path1, database_path2)
mac_t_ranked_df = filter_df(mac_t_pair_df)

 31%|███       | 7700/25198 [00:03<00:08, 2147.83it/s]/home/sxr280/miniconda3/envs/spatialformer/lib/python3.9/site-packages/scipy/stats/_axis_nan_policy.py:502: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/home/sxr280/miniconda3/envs/spatialformer/lib/python3.9/site-packages/scipy/stats/_stats_py.py:1214: RuntimeWarning: divide by zero encountered in divide
  var *= np.divide(n, n-ddof)  # to avoid error on division by zero
/home/sxr280/miniconda3/envs/spatialformer/lib/python3.9/site-packages/scipy/stats/_stats_py.py:1214: RuntimeWarning: invalid value encountered in double_scalars
  var *= np.divide(n, n-ddof)  # to avoid error on division by zero
100%|██████████| 25198/25198 [00:11<00:00, 2106.07it/s]
/home/sxr280/Spatialformer_6_10/utils/utils.py:1624: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["adj_P_value"] = pvals_corrected

In [5]:
mac_t_ranked_df[mac_t_ranked_df["ligand_receptor"] == True]

,gene_pair,gene1,gene2,Deduction,rank_mean,stat,P_value,support_num,top20_cellpairs,top20_diff,ligand_receptor,10log(1-D),symbol,adj_P_value
7156,"(ITGAV, COL1A1)",ITGAV,COL1A1,-0.020312,32.565217,-3.895819,1.130230e-04,69,"[[aaaaeoho-1, aaaaeoic-1], [aaaaeoic-1, aaaaeo...","[-0.23196593, -0.22898763, -0.0925262, -0.0904...",True,-0.296057,-1,0.000323
793,"(PTPRC, CD8A)",PTPRC,CD8A,-0.010044,32.016393,-3.072045,1.597111e-03,61,"[[aaaaeoig-1, aaaaeojp-1], [aaaaeojp-1, aaaaeo...","[-0.10751966, -0.09590387, -0.08065757, -0.069...",True,-0.145637,-1,0.002824
357,"(CD44, COL1A1)",CD44,COL1A1,-0.008778,16.872781,-3.236649,7.285054e-04,169,"[[aaaaeoho-1, aaaaeoic-1], [aaaaeoic-1, aaaaeo...","[-0.21668854, -0.21413094, -0.099544585, -0.09...",True,-0.127199,-1,0.001511
771,"(PTPRC, CD2)",PTPRC,CD2,-0.007068,30.337963,-5.156082,5.820141e-07,108,"[[aaaaeohp-1, aaaaeojf-1], [aaaaeoig-1, aaaaeo...","[-0.058948874, -0.05659622, -0.0524835, -0.049...",True,-0.102331,-1,0.000005
5445,"(COL1A2, ITGAV)",COL1A2,ITGAV,-0.006441,26.528986,-3.669050,2.397062e-04,69,"[[aaaaeokj-1, aaaaenka-1], [aaaaeoho-1, aaaaeo...","[-0.08048922, -0.035301983, -0.0326342, -0.032...",True,-0.093219,-1,0.000604
5097,"(PTPRC, CXCR4)",PTPRC,CXCR4,-0.004559,38.786957,-3.453905,3.882800e-04,115,"[[aaaaeojf-1, aaaaeojp-1], [aaaaeoig-1, aaaaeo...","[-0.07957831, -0.07580665, -0.059121907, -0.04...",True,-0.065920,-1,0.000894
351,"(CD44, COL1A2)",CD44,COL1A2,-0.004008,10.468391,-2.530486,6.141315e-03,174,"[[aaaaeojp-1, aaaaeojf-1], [aaaaeojf-1, aaaaeo...","[-0.11780578, -0.11045283, -0.08330029, -0.082...",True,-0.057938,-1,0.008383
5824,"(FN1, ITGAV)",FN1,ITGAV,-0.003743,37.492063,-2.512756,7.297003e-03,63,"[[aaaaeoic-1, aaaaeoho-1], [aaaaeoig-1, aaaaeo...","[-0.050908208, -0.03267318, -0.022529662, -0.0...",True,-0.054100,-1,0.009697
362,"(CD44, PTPRC)",CD44,PTPRC,-0.002299,22.673611,-2.035294,2.183419e-02,144,"[[aaaaeoig-1, aaaaeojp-1], [aaaaeojp-1, aaaaeo...","[-0.07166642, -0.053220868, -0.048924655, -0.0...",True,-0.033201,-1,0.024848

In [10]:
mac_t_ranked_df[(mac_t_ranked_df["gene1"] == "LYZ") | (mac_t_ranked_df["gene2"] == "LYZ")]

,gene_pair,gene1,gene2,Deduction,rank_mean,stat,P_value,support_num,top20_cellpairs,top20_diff,ligand_receptor,10log(1-D),symbol,adj_P_value
222,"(SOD2, LYZ)",SOD2,LYZ,-0.044512,18.620805,-7.425568,4.105922e-12,149,"[[aaaaeojf-1, aaaaeohp-1], [aaaaeojo-1, aaaaeo...","[-0.3312052, -0.31582475, -0.26745158, -0.2451...",False,-0.656907,-1,2.631188e-10
1968,"(SFTPC, LYZ)",SFTPC,LYZ,-0.033487,22.845794,-5.392771,2.121592e-07,107,"[[aaaaeokj-1, aaaaeoim-1], [aaaaeokj-1, aaaaen...","[-0.29881227, -0.269417, -0.25843066, -0.20551...",False,-0.491391,-1,2.032687e-06
24,"(CCL18, LYZ)",CCL18,LYZ,-0.028151,19.802158,-5.030113,7.495458e-07,139,"[[aaaaeojp-1, aaaaeojf-1], [aaaaeojf-1, aaaaeo...","[-0.40476292, -0.33298233, -0.20284843, -0.192...",False,-0.411964,-1,5.544434e-06
123,"(STAT1, LYZ)",STAT1,LYZ,-0.023112,20.711921,-4.893359,1.265693e-06,151,"[[aaaaenea-1, aaaaemlm-1], [aaaaeoho-1, aaaaeo...","[-0.31978148, -0.2984792, -0.27736205, -0.2294...",False,-0.337342,-1,8.473022e-06
3651,"(SFTPD, LYZ)",SFTPD,LYZ,-0.019781,39.233333,-3.344520,7.184844e-04,60,"[[aaaaeoig-1, aaaaeoho-1], [aaaaeoho-1, aaaaeo...","[-0.23946303, -0.23363626, -0.10556495, -0.096...",False,-0.288236,-1,1.493379e-03
74,"(HMOX1, LYZ)",HMOX1,LYZ,-0.017648,20.466667,-4.838767,1.978454e-06,120,"[[aaaaeojp-1, aaaaeojf-1], [aaaaeoim-1, aaaaeo...","[-0.20999306, -0.177275, -0.15157169, -0.11780...",False,-0.256879,-1,1.221058e-05
456,"(COL3A1, LYZ)",COL3A1,LYZ,-0.015885,18.080000,-3.074958,1.252513e-03,150,"[[aaaaeoin-1, aaaaeojp-1], [aaaaeojp-1, aaaaeo...","[-0.35635772, -0.2812107, -0.17984408, -0.1765...",False,-0.231006,-1,2.372935e-03
9101,"(CD3G, LYZ)",CD3G,LYZ,-0.012789,24.313559,-2.463063,8.382504e-03,59,"[[aaaaeoig-1, aaaaeoho-1], [aaaaeoho-1, aaaaeo...","[-0.19286346, -0.16305953, -0.12303966, -0.114...",False,-0.185693,-1,1.090918e-02
3685,"(COL1A1, LYZ)",COL1A1,LYZ,-0.009919,25.108108,-3.341953,5.275246e-04,148,"[[aaaaeoho-1, aaaaeoic-1], [aaaaeoic-1, aaaaeo...","[-0.21767044, -0.21709299, -0.09258109, -0.089...",False,-0.143813,-1,1.163793e-03
7071,"(KLRB1, LYZ)",KLRB1,LYZ,-0.008299,21.946429,-5.529729,4.565282e-07,56,"[[aaaaeojp-1, aaaaeoig-1], [aaaaeoig-1, aaaaeo...","[-0.04474777, -0.043800473, -0.03809172, -0.03...",False,-0.120236,-1,3.703769e-06
4326,"(CD8A, LYZ)",CD8A,LYZ,-0.008035,24.809524,-4.093811,6.244175e-05,63,"[[aaaaeoin-1, aaaaeojp-1], [aaaaeojp-1, aaaaeo...","[-0.06266159, -0.059951305, -0.05097747, -0.04...",False,-0.116384,-1,2.026336e-04
3892,"(IL7R, LYZ)",IL7R,LYZ,-0.007409,21.111765,-3.259677,8.057918e-04,85,"[[aaaaeoig-1, aaaaeojp-1], [aaaaeojp-1, aaaaeo...","[-0.12149668, -0.08326924, -0.08204466, -0.065...",False,-0.107283,-1,1.637629e-03
2115,"(NAPSA, LYZ)",NAPSA,LYZ,-0.007132,32.203704,-2.900607,2.260667e-03,108,"[[aaaaeojf-1, aaaaeojp-1], [aaaaeoig-1, aaaaeo...","[-0.12863895, -0.11538747, -0.11337331, -0.076...",False,-0.103262,-1,3.710002e-03
3795,"(CD2, LYZ)",CD2,LYZ,-0.007115,26.807692,-4.867927,2.040497e-06,104,"[[aaaaenje-1, aaaaenjg-1], [aaaaeojf-1, aaaaeo...","[-0.056931138, -0.051893294, -0.05152899, -0.0...",False,-0.103010,-1,1.251671e-05
2607,"(KRT18, LYZ)",KRT18,LYZ,-0.006849,37.535714,-3.010514,1.966407e-03,56,"[[aaaaeoic-1, aaaaeoho-1], [aaaaeoho-1, aaaaeo...","[-0.062297285, -0.057483792, -0.044243693, -0....",False,-0.099147,-1,3.308036e-03
877,"(COL1A2, LYZ)",COL1A2,LYZ,-0.006144,18.588235,-3.151956,9.770260e-04,153,"[[aaaaeojp-1, aaaaeojf-1], [aaaaeojf-1, aaaaeo...","[-0.1331555, -0.11719337, -0.1067009, -0.08991...",False,-0.088906,-1,1.927232e-03
643,"(VIM, LYZ)",VIM,LYZ,-0.005354,22.540373,-4.195976,2.245691e-05,161,"[[aaaaeojp-1, aaaaeojf-1], [aaaaeojf-1, aaaaeo...","[-0.084343255, -0.062495112, -0.05720395, -0.0...",False,-0.077453,-1,8.525151e-05
2307,"(GPR183, LYZ)",GPR183,LYZ,-0.004424,35.013699,-3.826571,1.371461e-04,73,"[[aaaaeojp-1, aaaaeojf-1], [aaaaeojf-1, aaaaeo...","[-0.03514588, -0.034823895, -0.030080616, -0.0...",False,-0.063972,-1,3.811297e-04
3290,"(CD68, LYZ)",CD68,LYZ,-0.004355,30.526316,-2.692807,4.194943e-03,95,"[[aaaaeoig-1, aaaaeoho-1], [aaaaeoho-1, aaaaeo...","[-0.06923807, -0.055475116, -0.053199947, -0.0...",False,-0.062965,-1,6.063381e-03
320,"(MS4A7, LYZ)",MS4A7,LYZ,-0.004285,28.325301,-1.682671,4.812154e-02,83,"[[aaaaeoim-1, aaaaeokj-1], [aaaaeokj-1, aaaaeo...","[-0.1409154, -0.119398415, -0.03593391, -0.033...",False,-0.061959,-1,4.831364e-02
4032,"(TRAC, LYZ)",TRAC,LYZ,-0.004195,28.117978,-3.206435,9.369744e-04,89,"[[aaaaeojf-1, aaaaeohp-1], [aaaaeoig-1, aaaaeo...","[-0.07245308, -0.039439976, -0.036983073, -0.0...",False,-0.060645,-1,1.855504e-03
2556,"(GCLM, LYZ)",GCLM,LYZ,-0.003933,33.865385,-3.465902,5.404780e-04,52,"[[aaaaeoho-1, aaaaeoig-1], [aaaaeoig-1, aaaaeo...","[-0.027730286, -0.024685979, -0.021202803, -0....",False,-0.056852,-1,1.179438e-03
8916,"(GSR, LYZ)",GSR,LYZ,-0.003754,32.824074,-3.108171,1.512503e-03,54,"[[aaaaeojp-1, aaaaeojf-1], [aaaaeojf-1, aaaaeo...","[-0.033311844, -0.031715184, -0.027521908, -0....",False,-0.054262,-1,2.731739e-03
5118,"(LYZ, CXCR4)",LYZ,CXCR4,-0.003662,33.964286,-2.786729,3.132087e-03,112,"[[aaaaeojf-1, aaaaeojp-1], [aaaaeojp-1, aaaaeo...","[-0.0881049, -0.08117783, -0.038446605, -0.022...",False,-0.052924,-1,4.810504e-03
4182,"(LYZ, HSPA5)",LYZ,HSPA5,-0.003329,32.907143,-4.035787,6.937893e-05,70,"[[aaaaeojf-1, aaaaeojp-1], [aaaaeojp-1, aaaaeo...","[-0.03273827, -0.020224512, -0.01645571, -0.01...",False,-0.048103,-1,2.208709e-04
786,"(PTPRC, LYZ)",PTPRC,LYZ,-0.003016,28.503817,-2.751171,3.393131e-03,131,"[[aaaaeojf-1, aaaaeojp-1], [aaaaeoig-1, aaaaeo...","[-0.05341488, -0.049026906, -0.0455274, -0.040...",False,-0.043576,-1,5.094761e-03
2778,"(PDIA3, LYZ)",PDIA3,LYZ,-0.003000,30.191057,-3.577018,2.496530e-04,123,"[[aaaaeojp-1, aaaaeojf-1], [aaaaeoho-1, aaaaeo...","[-0.03673315, -0.03314364, -0.031937003, -0.03...",False,-0.043345,-1,6.247535e-04
3522,"(HYOU1, LYZ)",HYOU1,LYZ,-0.002990,32.742647,-2.255799,1.367638e-02,68,"[[aaaaeojp-1, aaaaeojf-1], [aaaaeoho-1, aaaaeo...","[-0.031624258, -0.026662946, -0.026412755, -0....",False,-0.043201,-1,1.663657e-02
5113,"(LYZ, ITGAV)",LYZ,ITGAV,-0.002795,38.736364,-2.041419,2.305405e-02,55,"[[aaaaeoho-1, aaaaeoic-1], [aaaaeoic-1, aaaaeo...","[-0.04381329, -0.043078005, -0.015282989, -0.0...",False,-0.040386,-1,2.588435e-02
12197,"(MGST1, LYZ)",MGST1,LYZ,-0.002744,36.082278,-1.676072,4.886416e-02,79,"[[aaaaeoic-1, aaaaeoho-1], [aaaaeoic-1, aaaaeo...","[-0.038222373, -0.03622496, -0.033404946, -0.0...",False,-0.039644,-1,4.896150e-02
11059,"(ERLEC1, LYZ)",ERLEC1,LYZ,-0.002724,34.392157,-4.149271,6.467647e-05,51,"[[aaaaenik-1, aaaaenip-1], [aaaaenip-1, aaaaen...","[-0.01890713, -0.015502632, -0.013332903, -0.0...",False,-0.039346,-1,2.078739e-04
3966,"(IRF1, LYZ)",IRF1,LYZ,-0.002646,29.671429,-2.053293,2.191853e-02,70,"[[aaaaeoho-1, aaaaeoig-1], [aaaaeojo-1, aaaaeo...","[-0.035726607, -0.03156978, -0.024847567, -0.0...",False,-0.038220,-1,2.491530e-02
2645,"(XBP1, LYZ)",XBP1,LYZ,-0.002237,29.285124,-2.770950,3.239992e-03,121,"[[aaaaeoic-1, aaaaeoho-1], [aaaaeoho-1, aaaaeo...","[-0.034085214, -0.029898226, -0.025470674, -0....",False,-0.032314,-1,4.923614e-03
836,"(ATF4, LYZ)",ATF4,LYZ,-0.001967,29.209016,-1.940890,2.729859e-02,122,"[[aaaaenje-1, aaaaenjg-1], [aaaaeoho-1, aaaaeo...","[-0.038599133, -0.024202883, -0.024157405, -0....",False,-0.028402,-1,2.985475e-02
4282,"(CD3E, LYZ)",CD3E,LYZ,-0.001897,24.411458,-1.726076,4.379236e-02,96,"[[aaaaeojp-1, aaaaeojf-1], [aaaaeojf-1, aaaaeo...","[-0.037699103, -0.034883797, -0.032632053, -0....",False,-0.027392,-1,4.468064e-02
1689,"(PECAM1, LYZ)",PECAM1,LYZ,-0.001654,31.854839,-1.696571,4.743780e-02,62,"[[aaaaeojf-1, aaaaeojp-1], [aaaaeojp-1, aaaaeo...","[-0.031622678, -0.02572316, -0.0181306, -0.015...",False,-0.023883,-1,4.777019e-02
1877,"(HIF1A, LYZ)",HIF1A,LYZ,-0.001636,34.621429,-2.082849,2.048668e-02,70,"[[aaaaeoic-1, aaaaeoho-1], [aaaaeoho-1, aaaaeo...","[-0.025413394, -0.02471298, -0.017294705, -0.0...",False,-0.023616,-1,2.358078e-02