# CellphoneDB v5.0 running

The jupyter notebook aims to run the well-established tool, including CellChat and CellPhoneDB, to investigate the ligand-receptor pairs in the Xenium data.

For running the CellPhoneDB

In [42]:
from cellphonedb.src.core.methods import cpdb_statistical_analysis_method
import scanpy as sc
import pandas as pd

Loading the cropped Granuloma area

In [37]:
croped_adata = sc.read_h5ad("/home/sxr280/Spatialformer/downstream/cell_cell_communication/data/croped_sdata_VUILD96MF.h5ad")

In [39]:
croped_adata.obs

,cell_id,transcript_counts,control_probe_counts,control_codeword_counts,unassigned_codeword_counts,deprecated_codeword_counts,total_counts,cell_area,nucleus_area,region,Annotations,Niches,cell_types,Cell,cell_type
cell_id,,,,,,,,,,,,,,,
aaaaajjn-1,aaaaajjn-1,97,0,0,0,0,97,215.801719,6.276719,cell_circles,not available,NaN,not available,aaaaajjn-1,not available
aaaaajjo-1,aaaaajjo-1,98,0,0,0,0,98,80.062031,37.615156,cell_circles,B cells,T2,B cells,aaaaajjo-1,B cells
aaaaajkb-1,aaaaajkb-1,137,0,0,0,0,137,108.555625,31.473906,cell_circles,B cells,T2,B cells,aaaaajkb-1,B cells
aaaaajkc-1,aaaaajkc-1,132,0,0,0,0,132,56.851719,38.021563,cell_circles,B cells,T2,B cells,aaaaajkc-1,B cells
aaaaajkd-1,aaaaajkd-1,130,0,0,0,0,130,72.250000,46.827031,cell_circles,B cells,T2,B cells,aaaaajkd-1,B cells
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
aaaalbno-1,aaaalbno-1,178,0,0,0,0,178,206.273750,33.415625,cell_circles,T-cells,T2,T-cells,aaaalbno-1,T-cells
aaaalbob-1,aaaalbob-1,134,0,0,0,0,134,107.833125,38.879531,cell_circles,B cells,T2,B cells,aaaalbob-1,B cells
aaaalbog-1,aaaalbog-1,283,0,0,0,0,283,198.913281,75.004531,cell_circles,B cells,T9,B cells,aaaalbog-1,B cells
aaaalbol-1,aaaalbol-1,127,0,0,0,0,127,101.014531,25.739063,cell_circles,Plasma,T1,Plasma,aaaalbol-1,Plasma
aaaalbon-1,aaaalbon-1,157,0,0,0,0,157,165.813750,40.189062,cell_circles,B cells,T2,B cells,aaaalbon-1,B cells

In [34]:
croped_adata.obs.index = croped_adata.obs["cell_id"]

In [36]:
croped_adata.write_h5ad("/home/sxr280/Spatialformer/downstream/cell_cell_communication/data/croped_sdata_VUILD96MF.h5ad")

In [13]:
croped_adata.obs["cell_types"].value_counts()

cell_types
T-cells                      293
B cells                      135
Macrophages                  117
DCs                           93
Fibroblasts                   49
not available                 23
Plasma                        23
SPP1+ Macrophages             20
Venous                        19
Interstitial Macrophages      16
Proliferating Myeloid         12
SMCs                          11
Proliferating Lymphoid         7
Lipofibroblasts                3
Mast                           2
NK cells                       2
Proliferating Mesenchymal      2
Lymphatic/DCs                  1
Activated FBs                  1
Peribronchial FBs              1
gCap                           0
SCGB3A2+                       0
SCGB3A2+/SCGB1A1+              0
AT2                            0
Proliferating Epithelial       0
MUC5B+                         0
KRT5-/KRT17+                   0
FABP4+ Macrophages             0
Differentiating Ciliated       0
Ciliated                       0
Basal                          0
Arteriole                      0
Alveolar FBs                   0
Adventitial FBs                0
pDCs                           0
Name: count, dtype: int64

keep "Cell" and "cell_type" only two columns in the meta file

In [26]:
croped_adata.obs["Cell"] = croped_adata.obs["cell_id"]
croped_adata.obs["cell_type"] = croped_adata.obs["Annotations"]
croped_adata.obs[["Cell", "cell_type"]].to_csv("/home/sxr280/Spatialformer_6_10/downstream/cell_cell_communication/data/test_meta_VUILD96MF.txt", index = False, sep = "\t")

In [29]:
croped_adata.obs[["Cell", "cell_type"]]

             Cell      cell_type
2460   aaaaajjn-1  not available
2461   aaaaajjo-1        B cells
2464   aaaaajkb-1        B cells
2465   aaaaajkc-1        B cells
2466   aaaaajkd-1        B cells
...           ...            ...
45533  aaaalbno-1        T-cells
45536  aaaalbob-1        B cells
45541  aaaalbog-1        B cells
45546  aaaalbol-1         Plasma
45548  aaaalbon-1        B cells

[830 rows x 2 columns]

In [40]:
cpdb_results = cpdb_statistical_analysis_method.call(
         cpdb_file_path = "/home/sxr280/Spatialformer_6_10/downstream/cell_cell_communication/cpdb_database/v5.0.0/cellphonedb.zip",
         meta_file_path = "/home/sxr280/Spatialformer_6_10/downstream/cell_cell_communication/data/test_meta_VUILD96MF.txt",
         counts_file_path = "/home/sxr280/Spatialformer/downstream/cell_cell_communication/data/croped_sdata_VUILD96MF.h5ad",
         counts_data = 'hgnc_symbol',
         output_path = "/home/sxr280/Spatialformer_6_10/downstream/cell_cell_communication/data")

Reading user files...
The following user files were loaded successfully:
/home/sxr280/Spatialformer/downstream/cell_cell_communication/data/croped_sdata_VUILD96MF.h5ad
/home/sxr280/Spatialformer_6_10/downstream/cell_cell_communication/data/test_meta_VUILD96MF.txt
[ ][CORE][11/06/25-11:10:39][INFO] [Cluster Statistical Analysis] Threshold:0.1 Iterations:1000 Debug-seed:-1 Threads:4 Precision:3
[ ][CORE][11/06/25-11:10:42][INFO] Running Real Analysis
[ ][CORE][11/06/25-11:10:42][INFO] Running Statistical Analysis

100%|██████████| 1000/1000 [00:05<00:00, 166.70it/s]

[ ][CORE][11/06/25-11:10:48][INFO] Building Pvalues result

[ ][CORE][11/06/25-11:10:48][INFO] Building results
Saved deconvoluted to /home/sxr280/Spatialformer_6_10/downstream/cell_cell_communication/data/statistical_analysis_deconvoluted_06_11_2025_111048.txt
Saved deconvoluted_percents to /home/sxr280/Spatialformer_6_10/downstream/cell_cell_communication/data/statistical_analysis_deconvoluted_percents_06_11_2025_111048.txt
Saved means to /home/sxr280/Spatialformer_6_10/downstream/cell_cell_communication/data/statistical_analysis_means_06_11_2025_111048.txt
Saved pvalues to /home/sxr280/Spatialformer_6_10/downstream/cell_cell_communication/data/statistical_analysis_pvalues_06_11_2025_111048.txt
Saved significant_means to /home/sxr280/Spatialformer_6_10/downstream/cell_cell_communication/data/statistical_analysis_significant_means_06_11_2025_111048.txt

Visualization of the CellPhoneDB v5 results

In [43]:
p_value = pd.read_table("/home/sxr280/Spatialformer_6_10/downstream/cell_cell_communication/data/statistical_analysis_pvalues_06_11_2025_111048.txt")

In [50]:
p_value

,id_cp_interaction,interacting_pair,partner_a,partner_b,gene_a,gene_b,secreted,receptor_a,receptor_b,annotation_strategy,...,not available|Peribronchial FBs,not available|Plasma,not available|Proliferating Lymphoid,not available|Proliferating Mesenchymal,not available|Proliferating Myeloid,not available|SMCs,not available|SPP1+ Macrophages,not available|T-cells,not available|Venous,not available|not available
0,CPI-SS0322747C2,CEACAM5_CEACAM6,simple:P06731,simple:P40199,CEACAM5,CEACAM6,False,False,False,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
1,CPI-SS001BF66E8,CEACAM6_CEACAM6,simple:P40199,simple:P40199,CEACAM6,CEACAM6,False,False,False,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
2,CPI-SS04B37190C,CEACAM5_CD8A,simple:P06731,simple:P01732,CEACAM5,CD8A,True,False,True,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
3,CPI-SC08C485EAE,FN1_integrin_a3b1_complex,simple:P02751,complex:integrin_a3b1_complex,FN1,NaN,True,False,False,curated,...,1.000,1.000,1.000,1.000,1.000,0.004,1.000,1.000,0.012,1.000
4,CPI-SC0FA241084,CSPG4_integrin_a3b1_complex,simple:Q6UVK1,complex:integrin_a3b1_complex,CSPG4,NaN,False,False,False,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
5,CPI-SC08F923F07,FN1_integrin_aVb1_complex,simple:P02751,complex:integrin_aVb1_complex,FN1,NaN,True,False,False,curated,...,0.018,0.024,0.016,0.008,0.040,0.012,0.020,0.046,0.012,0.020
6,CPI-SC08AC51E15,TGFB1_integrin_aVb6_complex,simple:P01137,complex:integrin_aVb6_complex,TGFB1,NaN,True,False,False,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
7,CPI-SC0DA808D76,TGFB3_integrin_aVb6_complex,simple:P10600,complex:integrin_aVb6_complex,TGFB3,NaN,True,False,False,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
8,CPI-SS086CB298F,APLN_APLNR,simple:Q9ULZ1,simple:P35414,APLN,APLNR,True,False,True,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
9,CPI-SS06C0074BD,CCL21_CCR7,simple:O00585,simple:P32248,CCL21,CCR7,True,False,True,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
10,CPI-SS0DBFB8BEA,CCL2_ACKR1,simple:P13500,simple:Q16570,CCL2,ACKR1,True,False,True,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
11,CPI-SS05B7D3407,CCL5_ACKR1,simple:P13501,simple:Q16570,CCL5,ACKR1,True,False,True,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
12,CPI-SS0669CC233,CXCL14_CXCR4,simple:O95715,simple:P61073,CXCL14,CXCR4,True,False,True,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
13,CPI-SS0C2437E0D,CXCL13_CXCR5,simple:O43927,simple:P32302,CXCL13,CXCR5,True,False,True,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
14,CPI-SS004C23DCE,EREG_EGFR,simple:O14944,simple:P00533,EREG,EGFR,True,False,True,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
15,CPI-SS0C3906934,RSPO3_LGR5,simple:Q9BXY4,simple:O75473,RSPO3,LGR5,True,False,True,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
16,CPI-SS0EB5364D4,RSPO3_LGR6,simple:Q9BXY4,simple:Q9HBX8,RSPO3,LGR6,True,False,True,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
17,CPI-SS0D168412F,FASLG_FAS,simple:P48023,simple:P25445,FASLG,FAS,True,False,True,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
18,CPI-SS0C03F7CDC,VEGFA_KDR,simple:P15692,simple:P35968,VEGFA,KDR,True,False,True,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
19,CPI-SS0C95AC883,WNT2_SFRP2,simple:P09544,simple:Q96HF1,WNT2,SFRP2,True,False,False,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
20,CPI-SS0F05B138C,WNT3A_SFRP2,simple:P56704,simple:Q96HF1,WNT3A,SFRP2,True,False,False,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
21,CPI-SS03F33B34C,WNT5A_SFRP2,simple:P41221,simple:Q96HF1,WNT5A,SFRP2,True,False,False,curated,...,0.074,0.000,0.014,1.000,1.000,0.002,1.000,0.050,0.155,0.163
22,CPI-SS08F783A87,WNT7B_SFRP2,simple:P56706,simple:Q96HF1,WNT7B,SFRP2,True,False,False,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
23,CPI-SS05E7290A6,WNT2_SFRP4,simple:P09544,simple:Q6FHJ7,WNT2,SFRP4,True,False,False,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
24,CPI-SS02879E156,WNT3A_SFRP4,simple:P56704,simple:Q6FHJ7,WNT3A,SFRP4,True,False,False,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
25,CPI-SS0A21B9682,WNT5A_SFRP4,simple:P41221,simple:Q6FHJ7,WNT5A,SFRP4,True,False,False,curated,...,1.000,1.000,1.000,1.000,1.000,0.000,1.000,1.000,0.004,1.000
26,CPI-SS050373228,WNT7B_SFRP4,simple:P56706,simple:Q6FHJ7,WNT7B,SFRP4,True,False,False,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
27,CPI-SS09D4B2070,CD274_PDCD1,simple:Q9NZQ7,simple:Q15116,CD274,PDCD1,False,True,True,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
28,CPI-SS0452C6098,CD86_CD28,simple:P42081,simple:P10747,CD86,CD28,False,True,False,curated,...,1.000,0.206,0.030,1.000,1.000,1.000,1.000,0.000,1.000,1.000
29,CPI-SS0A72C2360,CD86_CTLA4,simple:P42081,simple:P16410,CD86,CTLA4,False,True,False,curated,...,1.000,1.000,0.035,1.000,1.000,1.000,1.000,0.000,1.000,1.000
30,CPI-SC00C58C990,LCK_CD8_receptor,simple:P06239,complex:CD8_receptor,LCK,NaN,False,False,True,curated,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
31,CPI-SS0822AEF5F,PTPRC_MRC1,simple:P08575,simple:P22897,PTPRC,MRC1,False,False,True,curated,...,1.000,0.936,0.799,0.487,0.038,0.719,0.118,0.934,0.928,0.243

In [55]:
p_value.loc[:,["interacting_pair", "Macrophages|T-cells", "T-cells|Macrophages", "T-cells|SPP1+ Macrophages","SPP1+ Macrophages|T-cells"]]

,interacting_pair,Macrophages|T-cells,T-cells|Macrophages,T-cells|SPP1+ Macrophages,SPP1+ Macrophages|T-cells
0,CEACAM5_CEACAM6,1.000,1.0,1.0,1.000
1,CEACAM6_CEACAM6,1.000,1.0,1.0,1.000
2,CEACAM5_CD8A,1.000,1.0,1.0,1.000
3,FN1_integrin_a3b1_complex,1.000,1.0,1.0,1.000
4,CSPG4_integrin_a3b1_complex,1.000,1.0,1.0,1.000
5,FN1_integrin_aVb1_complex,0.000,1.0,1.0,0.000
6,TGFB1_integrin_aVb6_complex,1.000,1.0,1.0,1.000
7,TGFB3_integrin_aVb6_complex,1.000,1.0,1.0,1.000
8,APLN_APLNR,1.000,1.0,1.0,1.000
9,CCL21_CCR7,1.000,1.0,1.0,1.000
10,CCL2_ACKR1,1.000,1.0,1.0,1.000
11,CCL5_ACKR1,1.000,1.0,1.0,1.000
12,CXCL14_CXCR4,1.000,1.0,1.0,1.000
13,CXCL13_CXCR5,1.000,1.0,1.0,1.000
14,EREG_EGFR,1.000,1.0,1.0,1.000
15,RSPO3_LGR5,1.000,1.0,1.0,1.000
16,RSPO3_LGR6,1.000,1.0,1.0,1.000
17,FASLG_FAS,1.000,1.0,1.0,1.000
18,VEGFA_KDR,1.000,1.0,1.0,1.000
19,WNT2_SFRP2,1.000,1.0,1.0,1.000
20,WNT3A_SFRP2,1.000,1.0,1.0,1.000
21,WNT5A_SFRP2,1.000,1.0,1.0,1.000
22,WNT7B_SFRP2,1.000,1.0,1.0,1.000
23,WNT2_SFRP4,1.000,1.0,1.0,1.000
24,WNT3A_SFRP4,1.000,1.0,1.0,1.000
25,WNT5A_SFRP4,1.000,1.0,1.0,1.000
26,WNT7B_SFRP4,1.000,1.0,1.0,1.000
27,CD274_PDCD1,1.000,1.0,1.0,1.000
28,CD86_CD28,0.000,1.0,1.0,0.000
29,CD86_CTLA4,0.000,1.0,1.0,0.014
30,LCK_CD8_receptor,1.000,1.0,1.0,1.000
31,PTPRC_MRC1,0.996,0.0,0.0,0.638

Visualizing in-situ on the spatial image in the tutorial notebook, refer to that one